// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/5/2026, 9:47:32 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/mizo/mizomade_web_intern/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/mizo/mizomade_web_intern/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/mizo/mizomade_web_intern/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/mizo/mizomade_web_intern/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/mizo/mizomade_web_intern/app/plugins/**/*.{js,ts,mjs}","D:/mizo/mizomade_web_intern/app/composables/**/*.{js,ts,mjs}","D:/mizo/mizomade_web_intern/app/utils/**/*.{js,ts,mjs}","D:/mizo/mizomade_web_intern/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/mizo/mizomade_web_intern/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/mizo/mizomade_web_intern/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/mizo/mizomade_web_intern/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;